### ISSUE TITLE
Missing to add step in /chat-workflow-spring-boot-starter/README.md file

### ISSUE THREAD

**Issue by amsidhlokhande** [finos/symphony-java-toolkit#149]
As we are getting same action even after submitting the same on symphony bot. 
In order to resolve this we need to add one below step in the readme file 

You will need to add the src\main\resources\META-INF\spring-devtools.properties for a bot with below content in it.

restart.include.chat-workflow=/chat-workflow-\\w\\d-\.+\.jar

**Comment by robmoffat** [comment]
Should we add this to chat-workflow, so it's always there?
