### ISSUE TITLE
Error Reporting Could Be Better

### ISSUE THREAD

**Issue by robmoffat** [finos/symphony-java-toolkit#163]
## Bug Report
 
IT seems like error's are always lost in the log when something goes wrong in chat workflow:  

![image](https://user-images.githubusercontent.com/568673/114584341-7c487a80-9c7a-11eb-987b-d9f7b9ad2981.png)

Fix it so that the java error message is shown, and the full stack trace is available if expanded, or as an attachment or something.

**Comment by amsidhlokhande** [comment]
code fixes are done

**Comment by robmoffat** [comment]
Please can you make sure there are some Unit tests for this:

1. Throws Exception
2. Throws Throwable w/o Cause
3. Throws Throwable with Cause
