### ISSUE TITLE
spring-devtools.properties file can be moved to parent dependency i.e chat-workflow-spring-boot-starter

### ISSUE THREAD

**Issue by amsidhlokhande** [finos/symphony-java-toolkit#169]
### Description of Problem:
Every time whenever we create chat work flow we were need to add this spring-devtools.properties file to resources/META-INF. This file contains the static content which is independent to any chat work flow app.  

...please resist the temptation to describe your request in terms of a solution.  Job Story form ("When [triggering condition], I want to [motivation/goal], so I can [outcome].") can help ensure you're expressing a problem statement.

### Potential Solutions:
We can move this file to parent dependency i.e  chat-workflow-spring-boot-starter project so that it will automatically get included in the chat workflow application.

**Comment by robmoffat** [comment]
Didn’t we already do this?
