### ISSUE TITLE
Delete Button / Checkbox Alignment

### ISSUE THREAD

**Issue by robmoffat** [finos/symphony-java-toolkit#171]
For some reason, Symphony doesn't support text-align on a <td> containing a checkbox.  This means our (Delete) buttons and checkboxes don't align on the screen.

Find some way to minimize how bad this looks

**Comment by robmoffat** [comment]
Also the NEW/EDIT buttons get a lot of space on the right... why is that?

**Comment by amsidhlokhande** [comment]
I will check and will do as required
